import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Roboto, Lora, Montserrat } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'], // Specify character subsets
  weight: ['400', '700'], // Add font weights
  style: ['normal', 'italic'], // Add styles if needed
});

const lora = Lora({
  subsets: ['latin'],
  weight: ['400'],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // {`${geistSans.variable} ${geistMono.variable} antialiased`}
      style={{background: 'rgb(214 211 209 / var(--tw-bg-opacity, 1))', color: 'rgb(0 0 0 / var(--tw-text-opacity, 1))'}}
        className={`${roboto.className} ${lora.className} ${montserrat.className}`}
      >
        {children}
      </body>
    </html>
  );
}
